MAX_RECORDS = 512

NUM_META = 6
INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
IS_DELETED = 4
BASE_RID_COLUMN = 5

TAIL_HANDLE = 5
MAX_NUM_RECORD = 512
INT_SIZE = 8
BUFFER_SIZE = 2000
